### ISSUE TITLE
please add a lot more c Examples and a c api documentation

### ISSUE THREAD

**Issue by MajidAbdelilah** [LukasBanana/LLGL#100]
hi
thanks a lot for your magnificent work, its truly such a wonderful technology to be able to port your engine from platform to platform and from a graphics api to another without having to redo your code base 
but fortunately the c examples are not enough for learning the library api  in c
i am a c developer i have worked with c++ a long time ago and i have escaped the hell of c++ becos of how horrible the syntax is it's truly an ugly pie of garbage compared to the clean c syntax 
for me and for many other c++ is a no go for us, its so hard to understand the code becoz of the syntax and i really really want to use your library for my future project but i have a hard time understanding and converting the c++ examples to c
if you can do more c examples and a c api documentation many developers would have a much easier time understanding how the library work, it would be a waste of time and effort to build the wrapper with no way of people to use it
thanks;

**Comment by LukasBanana** [comment]
Examples are one of the best ways to get people to start using a library for sure. If there is more interest in the C API, I can start porting some of the examples to C. Since I do that in my spare time, however, I won't be able to give you a proper estimate but I keep that in mind and see if I can update some of them soon-ish.

I would still advice you to look at the C++ documentation at least to know how the descriptor structures are default initialized since that's something that would have to be done with separate C functions or macros that don't exist (yet).

For some immediate help, I can probably update the [C99 Wrapper docs](https://github.com/LukasBanana/LLGL/tree/master/include#c99-wrapper) with some more info about the overall design of the wrapper.

**Comment by LukasBanana** [comment]
For some general questions, please feel free to make use of the [discussions section](https://github.com/LukasBanana/LLGL/discussions). I haven't used it yet, but perhaps I can answer some of your questions there.

**Comment by LukasBanana** [comment]
I just added a new C99 example: "Offscreen" (See [example](https://github.com/LukasBanana/LLGL/tree/master/examples/C99) page).
Please feel free to make any more example suggestions in the discussion section.
