### ISSUE TITLE
Build Script Rundown?

### ISSUE THREAD

**Issue by ForgeMistress** [LukasBanana/LLGL#26]
I'm mulling over the cmakelists file to see how I can port it over to premake5 for my own personal project, but I was wondering if you guys could give me a rundown on the build flags and such that need to be set in order to build it properly. Since the library can only get the full range of features when built as a shared library, I am definitely going to be doing that at least, but is there anything else I shod be aware of? Any gotchas or quirks I should know about?

**Comment by LukasBanana** [comment]
I'm not aware of premake5 but maybe these infos will help you:

**Disabled warnings:**

A couple of MSVC warnings are disabled, because LLGL exposes STL containers over the DLL boundary at some point. I know this is considered bad practice, because it makes the ABI incompatible between different compilers or compiler-versions (e.g. MSVC12 vs MSVC14). However, I always use the same compiler for all libraries and projects that are dependent on each other (And by the way: I hate to use C-style raw pointers all over a library's interface that is actually written in *modern* C++11).

These are the affected warnings for VisualC++:
```CMake
add_definitions(-D_CRT_SECURE_NO_WARNINGS)
add_definitions(-D_SCL_SECURE_NO_WARNINGS)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4250 /wd4251 /wd4290 /wd4103")
```

**Library Suffix for Debug Version:**

It's important to add the `D` suffix to the name of the shared libraries, because LLGL will extend the input module name to the respective build version.
I.e. when loading the renderer `"OpenGL"` LLGL will extend this name to `"LLGL_OpenGL.dll"` on a release build and to `"LLGL_OpenGLD.dll"` on a debug build for Windows. Same goes for Linux and MacOS, expect other file extensions are used.
In CMake, this is done like this:
```CMake
set_target_properties(LLGL_OpenGL PROPERTIES LINKER_LANGUAGE CXX DEBUG_POSTFIX "D")
```

**Strict C++11 Featureset:**

This library is written entirely in C++11, no C++14 feature is used. This is why `std::make_unique` is written manually in the library. But at least the `-std=c++11` feature set must be enabled for GCC and Clang.
In CMake, this is done by explicitly enabling a certain C++11 feature:
```CMake
target_compile_features(${PROJECT_NAME} PRIVATE cxx_range_for)
```

**Progress of the Backends:**

In the CMake file, there is a project setting for **OpenGLES**, but you can ignore that (it's not even close to be named an "experimental state"). The renderers that are almost fully supported (in relation to the LLGL interface) are **OpenGL** and **Direct3D11**. The renderers that are either partially supported or still in an experimental state are **Vulkan**, **Direct3D12**, and **Metal**.

Hope this helps for the beginning.

**Comment by ForgeMistress** [comment]
Thanks a lot! This will definitely help me make the premake script. I'll be sure to post the final script when I have it all working so others can use it.
