### ISSUE TITLE
how to debug low level api ? 

### ISSUE THREAD

**Issue by CaichaoGitHub** [LukasBanana/LLGL#33]
i want to debug low level api while using clion, however , i found the target version of render system is loaded dynamically using dlopen , its possible to debug the OPENGL api ?
![2019-03-05 11 23 31](https://user-images.githubusercontent.com/12059897/53778870-3ff1ae80-3f39-11e9-97a9-afedde152397.png)

**Comment by LukasBanana** [comment]
The debug layer (i.e. `DbgRenderSystem`) is always linked statically because it's part of the LLGL.lib and not another dynamically loaded library (like LLGL_OpenGL.lib for instance).

In VisualStudio, debugging dynamically loaded libraries is not a big deal, but if it doesn't work on your platform, just build the entire LLGL project as static lib (i.e. with the CMake option `LLGL_BUILD_STATIC_LIB` enabled). In this case, however, you can only build a single render system:

![llgl-cmake-issue33](https://user-images.githubusercontent.com/3158638/53790262-db2d5880-3f26-11e9-9cd8-62504074a23e.png)

**Comment by CaichaoGitHub** [comment]
> The debug layer (i.e. `DbgRenderSystem`) is always linked statically because it's part of the LLGL.lib and not another dynamically loaded library (like LLGL_OpenGL.lib for instance).
> 
> In VisualStudio, debugging dynamically loaded libraries is not a big deal, but if it doesn't work on your platform, just build the entire LLGL project as static lib (i.e. with the CMake option `LLGL_BUILD_STATIC_LIB` enabled). In this case, however, you can only build a single render system:
> 
> ![llgl-cmake-issue33](https://user-images.githubusercontent.com/3158638/53790262-db2d5880-3f26-11e9-9cd8-62504074a23e.png)

i build llg in  static lib and it worked , thanks ,
