### ISSUE TITLE
License

### ISSUE THREAD

**Issue by julianxhokaxhiu** [LukasBanana/LLGL#52]
Hi,

I was checking the License more carefully and I noticed that this library is using none of the well-known licenses. Therefore I was here to actually ask if there is a plan on using anyone of them like MIT, Apache or GPL?

I was planning in using this in one of my projects, but at the current state I'm a bit concerned about consequences in using your code on top of mine.

Thank you in advance for any clarification given.

**Comment by NoFr1ends** [comment]
3-Clause BSD License is well known?
https://opensource.org/licenses/BSD-3-Clause

**Comment by LukasBanana** [comment]
I'm using the **BSD 3-Clause** license, which I maybe should make more explicitly visible.
But it's very similar to MIT and zlib/libpng license. Even the Linux kernel uses the BSD 2-Clause to which the 3-Clause version is only an extension with a 3rd clause which prohibits _promoting_ a derived project with the name of the original author without written permission.

I don't see how this is an issue for open source projects. BSD 3-Clause is even an approved by the [Open Source Initiative](https://opensource.org/licenses/BSD-3-Clause). You can use LLGL for both open-source and closed-source as well as commercial and non-commercial projects.

GPL is a no-go for me, because you basically need a lawyer to fully understand the wall of text and makes the library inaccessible for closed-source projects.
Only the LGPL allows to load open-source libraries into closed-source projects via _dynamic linkage_, which I don't want LLGL limit to either.

**Comment by julianxhokaxhiu** [comment]
Nice and clear! I'm usually using MIT for all my projects, but I missed that this is a BSD 2-Clause. If you could update the license to better reflect that it would make it perfect.

Thank you!

**Comment by LukasBanana** [comment]
Sorry for the misunderstanding, but this is a **BSD 3-Clause**, I only said it's basically an _extension_ to the BSD 2-Clause.
I can add this information to the LICENSE.txt file to make it more clear though.

**Comment by LukasBanana** [comment]
Btw: The BSD version is explicitly mentioned in the README.md file: https://github.com/LukasBanana/LLGL#license

I'd like to avoid touching the LICENSE.txt file and most other projects using this license seem to have the same scheme, i.e. not explicitly mentioning the license version in the header.

**Comment by julianxhokaxhiu** [comment]
Actually fixing the LICENSE.txt file would also provide the information on Github on the Repository information bar, on the far right side.

But it's fine, being in the README is fine :) My bad, I skipped checking it there. Thanks anyway!
