### ISSUE TITLE
Primitive restart index not working on Mac OpenGL

### ISSUE THREAD

**Issue by beldenfox** [LukasBanana/LLGL#72]
The code that sets up the fixed primitive restart index (`GLStateManager::SetPrimitiveRestartIndex`) only sets the index if the `ARB_compatibility` extension is present even though `glPrimitiveRestartIndex` is a core feature of OpenGL 3.1 and up.

**Comment by LukasBanana** [comment]
This should be fixed with commit 0543649. I enabled the `GL_ARB_compatibility` extension by default for Mac, but haven't committed that change until now. I also enable the GL state `GL_PRIMITIVE_RESTART`only when an index buffer is bound, as this was causing a triangle soup when the non-indexed `Draw` commands were used on Mac.
