### ISSUE TITLE
Allow for aggregate initialization in descriptors 

### ISSUE THREAD

**Issue by IyadHamid** [LukasBanana/LLGL#84]
I noticed that there are a lot of structures with unnecessary constructors which just emulate aggregate initialization. Would it be possible to remove the various constructors/assignment operators to allow for aggregate initialization. This would also allow for C++20's designated initialization if compiling with C++20.

**Comment by LukasBanana** [comment]
It's true there are several constructors to emulate aggregate initialization, but the reason is that aggregate initialization does not work in conjunction with default initializers, at least not in C++11. According to cppreference.com, a struct with default member initializers is not an aggregate until C++14:
https://en.cppreference.com/w/cpp/language/aggregate_initialization
The idea for default initializers in the public interfaces is purely for stability.

Are there any particular structs that bother you to have such constructors or are there any structs missing such constructors?

**Comment by IyadHamid** [comment]
Ah, I didn't realize that default member initialization prevented it being an aggregate until C++14. In my project I am using C++20 to see how the modern features would play with low level graphics. Luckily most of the large descriptors (e.g. `GraphicsPipelineDescriptor`) are considered aggregates and allow for greater readability if I am constructing the descriptor within the function call. 

The descriptors I noted not having aggregation in C++20 were `ResourceHeapDescriptor`, `BindingDescriptor`, and `ShaderDescriptor`; although none of them were much of a bother. 

Using explicit constructors to specify how many members should be initialized at once is a good idea, however, to keep with aggregate initialization with this constraint, you could make helper utility functions to construct it so designated initializers can still be made to whoever wants to (much like `VertexBufferDesc` and similar).

Overall I think the library is great and thanks for making it.

**Comment by LukasBanana** [comment]
Thank you for your feedback.
`VertexBufferDesc` is one of the utiliy functions, but perhaps it's not a bad idea to switch to more of those instead of holding aggregate initialization for C++20 compilers back. I might also consider just bumping up the minimum C++ version to C++14 at some point.

**Comment by LukasBanana** [comment]
This ticket got a bit stale. I haven't bumped up the C++ standard requirement for this project but if you are interested in more of the utility functions to initialize the descriptor structs, please feel free to open a new thread in the discussion section.
